# ============================
# -=-=-= MySQL Settings =-=-=-
# ============================
# MySQL Database
mysql:
    driver: com.mysql.jdbc.Driver
    host: jdbc:mysql://localhost
    username: root
    password: root
    database: novauniverse

# =============================
# -=-=-= Server Settings =-=-=-
# =============================
lobby_server_type: lobby

# The name of the default server configured in the settings for bungeecord 
default_server_name: void