main: net.novauniverse.main.NovaMain
name: NovaMain
description: BABABOOEY
version: 1.0
api-version: 1.13
softdepend: [LabyModAPI, ProtocolLib, NovaCoreGameEngine]

depend: [NovaCore]

loadbefore: [NovaGamesTarget]
